### ISSUE TITLE
Minor typo in installation docs

### ISSUE THREAD

**Issue by liamhuber** [sntioudis/papreca#1]
> `cmake -DPKG_MOLECULE=on -DPKG_RIGID=on -D PKG_QEQ=on -DPKG_REAXFF=on -DBUILD_LIB=on -DBUILD_SHARED_LIBS=off -DBUILD_STATIC_LIBS=on ../cmake #Configure LAMMPS, build with some optional package, and enable static library building`

[Here](https://github.com/sntioudis/papreca/blob/23072ca67ad6708bce75b33efeb33586f347f92c/documentation/installation.md?plain=1#L31)

Should have `-D PKG_QEQ=on` --> `-DPKG_QEQ=on`. Very minor, but nice to fix for those copying and pasting.

**Comment by sntioudis** [comment]
@liamhuber thank you for that! I just fixed that. Should be now updated in the documentation!

**Comment by sntioudis** [comment]
@liamhuber thank you for that! I just fixed that. It should now be updated in the documentation!

**Comment by liamhuber** [comment]
Yep, just refreshed the docs tab and it's already live! 🚀

**Comment by liamhuber** [comment]
Ah, and for completeness I'm coming here from https://github.com/openjournals/joss-reviews/issues/6714, although this certainly wasn't anything like a blocking issue.
