### ISSUE TITLE
Tests: fail on physics failure

### ISSUE THREAD

**Issue by liamhuber** [sntioudis/papreca#10]
An issue for https://github.com/openjournals/joss-reviews/issues/6714 (I'm on the fence whether it should be blocking)

I am very happy that the event types are [all](https://github.com/sntioudis/papreca/blob/main/tests/event%20tests/test_all_events.sh) getting [tested](https://github.com/sntioudis/papreca/blob/0f10dc3625b5342d8c8ae7e38b567baa40a1231a/.github/workflows/run_ALLtests.yml#L76). If papreca actually fails for any of them, you nicely get a bad exit ([e.g.](https://github.com/sntioudis/papreca/blob/0f10dc3625b5342d8c8ae7e38b567baa40a1231a/tests/event%20tests/formation%20events/test_formations.py#L101)). Further, the various `compareArraysAndPrintStats` nicely give some human-readable report on actual metrics from the run. However, these metrics can be absolutely garbage and the test will still pass; the test itself should be made to fail if the printed metrics would concern a human reader.

**Comment by sntioudis** [comment]
All the event test python scripts now exit with 1 if the test success rate is 100% and with 0 if the test success rate is less than 100%. 

The test_all_events.sh bash script has also been updated to retrieve the relevant python script exit codes. If any of the python scripts returns  1, then the bash script will prematurely exit with code 1 causing the GitHub workflow to fail.
