### ISSUE TITLE
Installation comments: Add note for mpicxx compiler in documentation (i.e., define DCMAKE_CXX_COMPILER for cmake)

### ISSUE THREAD

**Issue by jfaraudo** [sntioudis/papreca#16]
I tried to install papreca in a machnie with a fresh install of Fedora Linux.
LAMMPS library was build as a fresh install following papreca documentation instructions , this is OK.

Now, when trying ti build papreca with cmak I had the following problem:

First, I did the cmake without errors or warnings:

cmake ../Installation/CMake -DLAMMPS_SRC_DIR=/home/jfaraudo/src -DLAMMPS_LIB_DIR=/home/jfaraudo/mylammps/build
-- Found LAMMPS library: /home/jfaraudo/mylammps/build/liblammps.a
-- Configuring additional packages...
CMake Warning at CMakeLists.txt:59 (message):
  PAPRECA does not use OpenMP, JPEG, and PNG packages.  However, the LAMMPS
  library uses them and therefore, we need to compile against those libraries
  to avoid linkage errors.  Depending on how YOUR LAMMPS library was built
  (i.e., based on the LAMMPS packages you enabled) you might need to enable
  additional libraries in the PAPRECA CMakeLists.txt file.

-- Configuring done (1.3s)
-- Generating done (0.0s)
-- Build files have been written to: /home/jfaraudo/papreca-main/build

So everything looks OK here. But then when doing the build I had this error:

jfaraudo@pcd31c:~/papreca-main/build$ cmake --build .
[  4%] Building CXX object CMakeFiles/PAPRECA_LIBRARY.dir/home/jfaraudo/papreca-main/source/libraries/PAPRECA/bond.cpp.o
In file included from /home/jfaraudo/papreca-main/source/libraries/PAPRECA/bond.cpp:23:
/home/jfaraudo/papreca-main/source/libraries/PAPRECA/bond.h:35:10: fatal error: pointers.h: No such file or directory
   35 | #include "pointers.h"
      |          ^~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/PAPRECA_LIBRARY.dir/build.make:76: CMakeFiles/PAPRECA_LIBRARY.dir/home/jfaraudo/papreca-main/source/libraries/PAPRECA/bond.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:85: CMakeFiles/PAPRECA_LIBRARY.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2

Any ideas?

**Comment by jfaraudo** [comment]
Oh!! Obviously this is the error, I missed the lammps folder . Sorry

**Comment by jfaraudo** [comment]
Now I get the follwoing error.
I removed everything of course and I started over.

The preparation of CMake was OK:
jfaraudo@pcd31c:~/papreca-main/build$ cmake ../Installation/CMake -DLAMMPS_SRC_DIR=/home/jfaraudo/mylammps/src -DLAMMPS_LIB_DIR=/home/jfaraudo/mylammps/build
-- The C compiler identification is GNU 13.2.1
-- The CXX compiler identification is GNU 13.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found LAMMPS library: /home/jfaraudo/mylammps/build/liblammps.a
-- Configuring additional packages...
CMake Warning at CMakeLists.txt:59 (message):
  PAPRECA does not use OpenMP, JPEG, and PNG packages.  However, the LAMMPS
  library uses them and therefore, we need to compile against those libraries
  to avoid linkage errors.  Depending on how YOUR LAMMPS library was built
  (i.e., based on the LAMMPS packages you enabled) you might need to enable
  additional libraries in the PAPRECA CMakeLists.txt file.


-- Found MPI_C: /usr/lib64/openmpi/lib/libmpi.so (found version "3.1") 
-- Found MPI_CXX: /usr/lib64/openmpi/lib/libmpi_cxx.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- Configuring done (2.4s)
-- Generating done (0.0s)
-- Build files have been written to: /home/jfaraudo/papreca-main/build

And now the build:

jfaraudo@pcd31c:~/papreca-main/build$ cmake --build .
[  4%] Building CXX object CMakeFiles/PAPRECA_LIBRARY.dir/home/jfaraudo/papreca-main/source/libraries/PAPRECA/bond.cpp.o
[  9%] Building CXX object CMakeFiles/PAPRECA_LIBRARY.dir/home/jfaraudo/papreca-main/source/libraries/PAPRECA/debug.cpp.o
[ 14%] Building CXX object CMakeFiles/PAPRECA_LIBRARY.dir/home/jfaraudo/papreca-main/source/libraries/PAPRECA/equilibration.cpp.o
[ 19%] Building CXX object CMakeFiles/PAPRECA_LIBRARY.dir/home/jfaraudo/papreca-main/source/libraries/PAPRECA/event.cpp.o
[ 23%] Building CXX object CMakeFiles/PAPRECA_LIBRARY.dir/home/jfaraudo/papreca-main/source/libraries/PAPRECA/event_detect.cpp.o
[ 28%] Building CXX object CMakeFiles/PAPRECA_LIBRARY.dir/home/jfaraudo/papreca-main/source/libraries/PAPRECA/event_execute.cpp.o
[ 33%] Building CXX object CMakeFiles/PAPRECA_LIBRARY.dir/home/jfaraudo/papreca-main/source/libraries/PAPRECA/event_list.cpp.o
[ 38%] Building CXX object CMakeFiles/PAPRECA_LIBRARY.dir/home/jfaraudo/papreca-main/source/libraries/PAPRECA/event_select.cpp.o
[ 42%] Building CXX object CMakeFiles/PAPRECA_LIBRARY.dir/home/jfaraudo/papreca-main/source/libraries/PAPRECA/export_files.cpp.o
[ 47%] Building CXX object CMakeFiles/PAPRECA_LIBRARY.dir/home/jfaraudo/papreca-main/source/libraries/PAPRECA/geometry_calc.cpp.o
[ 52%] Building CXX object CMakeFiles/PAPRECA_LIBRARY.dir/home/jfaraudo/papreca-main/source/libraries/PAPRECA/input_file.cpp.o
[ 57%] Building CXX object CMakeFiles/PAPRECA_LIBRARY.dir/home/jfaraudo/papreca-main/source/libraries/PAPRECA/lammps_wrappers.cpp.o
[ 61%] Building CXX object CMakeFiles/PAPRECA_LIBRARY.dir/home/jfaraudo/papreca-main/source/libraries/PAPRECA/mpi_wrappers.cpp.o
[ 66%] Building CXX object CMakeFiles/PAPRECA_LIBRARY.dir/home/jfaraudo/papreca-main/source/libraries/PAPRECA/papreca_config.cpp.o
[ 71%] Building CXX object CMakeFiles/PAPRECA_LIBRARY.dir/home/jfaraudo/papreca-main/source/libraries/PAPRECA/papreca_error.cpp.o
[ 76%] Building CXX object CMakeFiles/PAPRECA_LIBRARY.dir/home/jfaraudo/papreca-main/source/libraries/PAPRECA/rates_calc.cpp.o
[ 80%] Building CXX object CMakeFiles/PAPRECA_LIBRARY.dir/home/jfaraudo/papreca-main/source/libraries/PAPRECA/sim_clock.cpp.o
[ 85%] Building CXX object CMakeFiles/PAPRECA_LIBRARY.dir/home/jfaraudo/papreca-main/source/libraries/PAPRECA/utilities.cpp.o
[ 90%] Linking CXX static library libPAPRECA_LIBRARY.a
[ 90%] Built target PAPRECA_LIBRARY
[ 95%] Building CXX object CMakeFiles/papreca.dir/home/jfaraudo/papreca-main/source/papreca.cpp.o
[100%] Linking CXX executable papreca
/usr/bin/ld: libPAPRECA_LIBRARY.a(lammps_wrappers.cpp.o): in function `PAPRECA::initializeLMP(LAMMPS_NS::LAMMPS**)':
lammps_wrappers.cpp:(.text+0x143): undefined reference to `LAMMPS_NS::LAMMPS::LAMMPS(int, char**, ompi_communicator_t*)'
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/papreca.dir/build.make:104: papreca] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/papreca.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2

What do you think?

**Comment by sntioudis** [comment]
Any chance you could also provide me with the cmake configuration output for LAMMPS as well? I need to check if there is a version mismatch between the MPI, and openMP libraries between LAMMPS and PAPRECA.

**Comment by sntioudis** [comment]
I tried to reproduce this error on my system but I failed. It looks like there is some sort of an MPI version mismatch (can happen if you have multiple versions of openMP or MPI in your system). It might also be that your LAMMPS installation did not finish properly or failed silently when trying to generate the LAMMPS library.

> /usr/bin/ld: libPAPRECA_LIBRARY.a(lammps_wrappers.cpp.o): in function PAPRECA::initializeLMP(LAMMPS_NS::LAMMPS**)': lammps_wrappers.cpp:(.text+0x143): undefined reference to LAMMPS_NS::LAMMPS::LAMMPS(int, char**, ompi_communicator_t*)'

This tells us that the linker could not find the constructor of the LAMMPS object.

Can you try to run this command and provide me with the output:

`nm -C /home/jfaraudo/mylammps/build/liblammps.a | grep LAMMPS_NS::LAMMPS::LAMMPS`

This might will let us know if there is a definition mismatch.

**Comment by sntioudis** [comment]
> Any chance you could also provide me with the cmake configuration output for LAMMPS? I need to check if there is a version mismatch between the MPI, and openMP libraries between LAMMPS and PAPRECA.

Can you also post your cmake build configuration for LAMMPS ?

**Comment by jfaraudo** [comment]
Here is
cmake -DPKG_MOLECULE=on -DPKG_RIGID=on -DPKG_QEQ=on -DPKG_REAXFF=on -DBUILD_LIB=on -DBUILD_SHARED_LIBS=off -DBUILD_STATIC_LIBS=on ../cmake
-- The CXX compiler identification is GNU 13.2.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.44.0") 
-- Running check for auto-generated files from make-based build system
-- Checking for module 'mpi-cxx'
--   Package 'mpi-cxx', required by 'virtual:world', not found
-- Looking for C++ include omp.h
-- Looking for C++ include omp.h - found
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5") found components: CXX 
-- Found GZIP: /usr/bin/gzip  
-- Could NOT find FFMPEG (missing: FFMPEG_EXECUTABLE) 
-- Looking for C++ include cmath
-- Looking for C++ include cmath - found
-- Generating style headers...
-- Generating package headers...
-- Generating lmpinstalledpkgs.h...
-- Found Python3: /usr/bin/python3.12 (found version "3.12.2") found components: Interpreter 
-- Could NOT find ClangFormat (missing: ClangFormat_EXECUTABLE) (Required is at least version "8.0")
-- The following tools and libraries have been found and configured:
 * Git
 * OpenMP
 * Python3

-- <<< Build configuration >>>
   LAMMPS Version:   20240417 patch_17Apr2024
   Operating System: Linux Fedora 39
   CMake Version:    3.27.7
   Build type:       RelWithDebInfo
   Install path:     /home/jfaraudo/.local
   Generator:        Unix Makefiles using /usr/bin/gmake
-- Enabled packages: MOLECULE;QEQ;REAXFF;RIGID
-- <<< Compilers and Flags: >>>
-- C++ Compiler:     /usr/bin/c++
      Type:          GNU
      Version:       13.2.1
      C++ Flags:     -O2 -g -DNDEBUG
      Defines:       LAMMPS_SMALLBIG;LAMMPS_MEMALIGN=64;LAMMPS_OMP_COMPAT=4;LAMMPS_GZIP
-- <<< Linker flags: >>>
-- Executable name:  lmp
-- Static library flags:    
-- Configuring done (4.9s)
-- Generating done (0.1s)
-- Build files have been written to: /home/jfaraudo/mylammps/build

**Comment by sntioudis** [comment]
Thank you!

I think I see what the issue is now. For some reason, LAMMPS does not detect MPI at all.

This is what your LAMMPS cmake configuration output should look like:

```
cmake -DPKG_MOLECULE=on -DPKG_RIGID=on -DPKG_QEQ=on -DPKG_REAXFF=on -DBUILD_LIB=on -DBUILD_SHARED_LIBS=off -DBUILD_STATIC_LIBS=on ../cmake #Configure LAMMPS, build with some optional package, and enable static library building
-- The CXX compiler identification is GNU 11.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.34.1") 
-- Running check for auto-generated files from make-based build system
-- Found MPI_CXX: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- Looking for C++ include omp.h
-- Looking for C++ include omp.h - found
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5") found components: CXX 
-- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so (found version "80") 
-- Found GZIP: /usr/bin/gzip  
-- Could NOT find FFMPEG (missing: FFMPEG_EXECUTABLE) 
-- Looking for C++ include cmath
-- Looking for C++ include cmath - found
-- Generating style headers...
-- Generating package headers...
-- Generating lmpinstalledpkgs.h...
-- Found Python3: /usr/bin/python3.10 (found version "3.10.12") found components: Interpreter 
-- Could NOT find ClangFormat (missing: ClangFormat_EXECUTABLE) (Required is at least version "8.0")
-- The following tools and libraries have been found and configured:
 * Git
 * MPI
 * OpenMP
 * JPEG
 * Python3

-- <<< Build configuration >>>
   LAMMPS Version:   20240417 patch_17Apr2024
   Operating System: Linux Ubuntu" 22.04
   CMake Version:    3.22.1
   Build type:       RelWithDebInfo
   Install path:     /home/sn120/.local
   Generator:        Unix Makefiles using /usr/bin/gmake
-- Enabled packages: MOLECULE;QEQ;REAXFF;RIGID
-- <<< Compilers and Flags: >>>
-- C++ Compiler:     /usr/bin/c++
      Type:          GNU
      Version:       11.4.0
      C++ Flags:     -O2 -g -DNDEBUG
      Defines:       LAMMPS_SMALLBIG;LAMMPS_MEMALIGN=64;LAMMPS_OMP_COMPAT=4;LAMMPS_JPEG;LAMMPS_GZIP
-- <<< Linker flags: >>>
-- Executable name:  lmp
-- Static library flags:    
-- <<< MPI flags >>>
-- MPI_defines:      MPICH_SKIP_MPICXX;OMPI_SKIP_MPICXX;_MPICC_H
-- MPI includes:     /usr/lib/x86_64-linux-gnu/openmpi/include;/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi
-- MPI libraries:    /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so;/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so;
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sn120/Desktop/LAMMPS/mylammps_17Apr2024/build
```

Notice that cmake informs me that *MPI has been correctly found and configured (the precise locations of MPI libraries are defined in the <<< MPI flags >>> section). Strangely enough, I can see that PAPRECA correctly identifies your MPI_CXX compiler:

> -- Found MPI_C: /usr/lib64/openmpi/lib/libmpi.so (found version "3.1")
-- Found MPI_CXX: /usr/lib64/openmpi/lib/libmpi_cxx.so (found version "3.1")
-- Found MPI: TRUE (found version "3.1")

Could you please uninstall LAMMPS and try to install it again by explicitly mentioning the name of the MPI compiler in your cmake command:

`cmake -DCMAKE_CXX_COMPILER=mpicxx -DPKG_MOLECULE=on -DPKG_RIGID=on -DPKG_QEQ=on -DPKG_REAXFF=on -DBUILD_LIB=on -DBUILD_SHARED_LIBS=off -DBUILD_STATIC_LIBS=on ../cmake`

Kindly let me know if your cmake configuration now correctly finds MPI before building.

If this works you can proceed by installing PAPRECA using a similar logic to generate your cmake configuration files:

`cmake ../Installation/CMake -DCMAKE_CXX_COMPILER=mpicxx -DLAMMPS_SRC_DIR=/home/jfaraudo/mylammps/src -DLAMMPS_LIB_DIR=/home/jfaraudo/mylammps/build`

**Comment by sntioudis** [comment]
Just a small note here: It might be better to explicitly define the compiler by its location.

1) Find the location of your mpicxx by running: `which mpicxx`
2) Copy and paste that location to your DCMAKE_CXX_COMPILER variable (i.e., if your mpicxx is located here:/usr/bin/mpicxx your variable should be -DCMAKE_CXX_COMPILER=/usr/bin/mpicxx

**Comment by jfaraudo** [comment]
Yeah, excellent suggestion . 
I did as you suggested. 
> which mpicxx
/usr/lib64/openmpi/bin/mpicxx
So then I did for LAMMPS:
cmake -DPKG_MOLECULE=on -DPKG_RIGID=on -DPKG_QEQ=on -DPKG_REAXFF=on -DBUILD_LIB=on -DBUILD_SHARED_LIBS=off -DBUILD_STATIC_LIBS=on -DCMAKE_CXX_COMPILER=/usr/lib64/openmpi/bin/mpicxx ../cmake
and for papreca:
 cmake ../Installation/CMake -DLAMMPS_SRC_DIR=/home/jfaraudo/mylammps/src -DLAMMPS_LIB_DIR=/home/jfaraudo/mylammps/build -DCMAKE_CXX_COMPILER=/usr/lib64/openmpi/bin/mpicxx

This solves the issue. I strongly suggest to add this to the building instructions, even this may sound trivial to you, it will be helpful to indicate that it is better to indicate the mpicxx compiler used.

**Comment by sntioudis** [comment]
Glad to hear that the issue has been solved and happy to help.

> This solves the issue. I strongly suggest to add this to the building instructions, even this may sound trivial to you, it will be helpful to indicate that it is better to indicate the mpicxx compiler used.

This is a fair point and thank you for your feedback. I will add those instructions to the documentation shortly!
