### ISSUE TITLE
Release management

### ISSUE THREAD

**Issue by liamhuber** [sntioudis/papreca#2]
Distribution via clone-and-build A-OK, but I like how lammps manages their versioning for this process, and recommend following a similar pattern. Namely, you can already make your first release tag (in contrast to lammps, I would strongly recommend using [semantic versioning](https://semver.org/) for such tags), then make a release branch and park it at that tag. Then in the installation docs add the same snippet you have for lammps -- `git checkout release; git pull` 

This is not a huge deal, but it will make it easy for you to have stable (release) and bleeding-edge (main) versions right out of the gate.

This is a non-blocking issue coming from https://github.com/openjournals/joss-reviews/issues/6714

**Comment by sntioudis** [comment]
This is a good point. I created a new (release) branch to address this and made the relevant changes to the documentation.
