### ISSUE TITLE
DFT and kMC not comparable

### ISSUE THREAD

**Issue by liamhuber** [sntioudis/papreca#5]
[From the paper.md](https://github.com/sntioudis/papreca/blob/0f10dc3625b5342d8c8ae7e38b567baa40a1231a/paper/paper.md?plain=1#L40):

> Overall, kMC techniques are, on one hand, less accurate, but on the other hand, more computationally efficient than other atomistic techniques such as the density functional theory (DFT) or molecular dynamics (MD).

I find the comparison to DFT to be apples-to-oranges, it's equivalent to saying "more computationally efficient that MEAM potentials". DFT is a tool for transforming structures (position+chemistry) into energies and forces (and electron density); kMC is a tool for evolving structures in time. In contrast, the comparison to MD is apples-to-apples. Indeed, one could use DFT (assuming arbitrarily powerful compute) and MD and kMC all together! So the real contrast here is kMC vs brute-force MD for temporal evolution.

IMO the comparison to brute-force MD is already sufficient and DFT should simply be removed. If you really want multiple items to contrast, you could consider mentioning some other acceleration technique, e.g. stuff by Danny Perez and Arthur Voter comes to mind.

**Comment by liamhuber** [comment]
Transferred from https://github.com/openjournals/joss-reviews/issues/6714

**Comment by sntioudis** [comment]
This is a valid point. Thank you both. I removed the DFT-kMC comparison and generated the paper again (see PAPRECA review issue for an updated version of the paper).
